import type { INodeTypeDescription } from '@nomops/workflow';

export const cryptoDescription: INodeTypeDescription = {
  displayName: 'Crypto',
  name: 'crypto',
  group: ['transform'],
  categories: ['dataTransformation'],
  aliases: ['hash', 'hmac', 'base64', 'uuid', 'encrypt', 'decrypt'],
  version: 1,
  description: 'Hash, encode, identify, encrypt, or decrypt values',
  defaults: { name: 'Crypto' },
  inputs: ['main'],
  outputs: ['main'],
  properties: [
    {
      displayName: 'Action',
      name: 'action',
      type: 'options',
      default: 'hash',
      noDataExpression: true,
      options: [
        { name: 'Hash', value: 'hash' },
        { name: 'HMAC', value: 'hmac' },
        { name: 'Base64 Encode', value: 'base64Encode' },
        { name: 'Base64 Decode', value: 'base64Decode' },
        { name: 'Generate UUID', value: 'uuid' },
        { name: 'Encrypt', value: 'encrypt' },
        { name: 'Decrypt', value: 'decrypt' },
      ],
    },
    {
      displayName: 'Value',
      name: 'value',
      type: 'string',
      default: '',
      required: true,
      displayOptions: { hide: { action: ['uuid'] } },
      description: 'UTF-8 value to process',
    },
    {
      displayName: 'Algorithm',
      name: 'algorithm',
      type: 'options',
      default: 'sha256',
      displayOptions: { show: { action: ['hash', 'hmac'] } },
      options: [
        { name: 'SHA-256', value: 'sha256' },
        { name: 'SHA-384', value: 'sha384' },
        { name: 'SHA-512', value: 'sha512' },
      ],
    },
    {
      displayName: 'Secret',
      name: 'secret',
      type: 'string',
      default: '',
      required: true,
      displayOptions: { show: { action: ['hmac', 'encrypt', 'decrypt'] } },
      description: 'HMAC secret or encryption passphrase',
    },
    {
      displayName: 'Digest Encoding',
      name: 'encoding',
      type: 'options',
      default: 'hex',
      displayOptions: { show: { action: ['hash', 'hmac'] } },
      options: [
        { name: 'Hex', value: 'hex' },
        { name: 'Base64', value: 'base64' },
      ],
    },
    {
      displayName: 'Output Field',
      name: 'outputField',
      type: 'string',
      default: 'data',
      required: true,
      description: 'Field that receives the processed value',
    },
  ],
};
